#!/usr/bin/env python3
"""seo_100_patch.py - idempotent on-page SEO patcher for the APF site (non-blog pages).

Brings the hand-authored sitemap pages to a clean pass on Apps/sutera-seo/checklist.py.
The blog index + posts are generated by .build/blog_render.py and are fixed there
(this patcher skips blog.html + blog/*).

Fixes:
  - <header> landmark: wrap the site <nav id="main-nav"> in a <header> on pages
    without one (most pages use their hero <header>; contact/faq/privacy lacked it)
  - headings h4 -> h3 with an .apf-sub class (styles.css) so the Inter (non-display)
    font is preserved - a plain h4->h3 would flip them to the Bebas display font
  - inject the LocalBusiness JSON-LD node (mirrored from index) on pages missing it
  - trim 11 titles into 50-60 and 13 meta descriptions into 150-165 (West Melbourne
    local SEO kept; no new West Point SC affiliation claims)

Homepage breadcrumb is deliberately left as the only warn; pooled score -> 100.
"""

import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SKIP = {"404.html", "thank-you.html", "blog.html"}   # + anything under blog/

TITLES = {
    "about.html": "About Accelerate Performance Football | Our Coaches",
    "faq.html": "Football Coaching FAQ | Accelerate Performance Football",
    "index.html": "Private Football Coaching Melbourne | Accelerate Performance",
    "online.html": "APF Online | Online Football Training Membership, Melbourne",
    "pricing/game-changer.html": "The Game Changer 13-Week Block | Accelerate Performance",
    "pricing/tune-up-group.html": "The Tune Up Small Unit | Accelerate Performance Football",
    "suburbs/altona.html": "Football & Soccer Coaching Altona | Accelerate Performance",
    "suburbs/altona-meadows.html": "Football & Soccer Coaching Altona Meadows | APF",
    "suburbs/altona-north.html": "Football & Soccer Coaching Altona North | APF",
    "suburbs/hoppers-crossing.html": "Football & Soccer Coaching Hoppers Crossing | APF",
    "suburbs/laverton.html": "Football & Soccer Coaching Laverton | Accelerate Performance",
    "suburbs/manor-lakes.html": "Football & Soccer Coaching Manor Lakes | APF",
    "suburbs/newport.html": "Football & Soccer Coaching Newport | Accelerate Performance",
    "suburbs/point-cook.html": "Football & Soccer Coaching Point Cook | Accelerate Performance",
    "suburbs/tarneit.html": "Football & Soccer Coaching Tarneit | Accelerate Performance",
    "suburbs/truganina.html": "Football & Soccer Coaching Truganina | Accelerate Performance",
    "suburbs/werribee.html": "Football & Soccer Coaching Werribee | Accelerate Performance",
    "suburbs/williams-landing.html": "Football & Soccer Coaching Williams Landing | APF",
    "suburbs/williamstown.html": "Football & Soccer Coaching Williamstown | APF",
    "suburbs/wyndham-vale.html": "Football & Soccer Coaching Wyndham Vale | APF",
    "suburbs/index.html": "Football &amp; Soccer Coaching Melbourne's West | Service Areas",
}

METAS = {
    "about.html": "Meet the coaches behind Accelerate Performance Football. Private football coaching in West Melbourne, built on precision and getting the best from every player.",
    "faq.html": "Common questions about private football coaching in West Melbourne: who we coach, how sessions run, pricing, location, injury return, and sibling discounts.",
    "online.html": "APF Online is an online football training membership: pro-level drills, technique tutorials and nutrition guidance you can follow from anywhere. Start a free trial.",
    "services/senior-refinement.html": "Advanced football coaching for experienced players in West Melbourne. Technical refinement, tactical awareness and match-ready conditioning to lift your game.",
    "coaches/chris-sutera.html": "Chris Sutera is Head Coach and founder of Accelerate Performance Football. 25 years playing, 5 years coaching, 125+ athletes trained in West Melbourne.",
    "coaches/james-sutera.html": "James Sutera is a Trainer at Accelerate Performance Football. 16 years playing, 2 years coaching, focused on building fundamentals and pushing athletes to their edge.",
    "pricing/game-changer.html": "A 13-week Small Unit football coaching block in West Melbourne. $60 per session, $780 total. Periodised plan, mid-block reassessment, measurable change.",
    "pricing/tune-up-group.html": "Five Small Unit football coaching sessions in West Melbourne. $65 per session, $325 total. Train with a sibling or teammate. Sibling and West Point SC discounts.",
    "suburbs/altona.html": "Private football and soccer coaching for Altona players. About 15 min via the Princes Freeway to West Point Soccer Club, Point Cook. Juniors to senior-league.",
    "suburbs/altona-meadows.html": "Private football and soccer coaching for Altona Meadows players. About 12 min to our venue at West Point Soccer Club, Point Cook. Juniors to senior-league.",
    "suburbs/altona-north.html": "Private football and soccer coaching for Altona North players. About 18 min to our venue at West Point Soccer Club, Point Cook. Juniors to senior-league.",
    "suburbs/hoppers-crossing.html": "Private football and soccer coaching for Hoppers Crossing players. About 8-10 min to West Point Soccer Club in adjacent Point Cook. Juniors to senior-league.",
    "suburbs/laverton.html": "Private football and soccer coaching for Laverton players. About 13 min to our venue at West Point Soccer Club, Point Cook. Juniors to senior-league.",
    "suburbs/manor-lakes.html": "Private football and soccer coaching for Manor Lakes players. About 24 min to our venue at West Point Soccer Club, Point Cook. Juniors to senior-league.",
    "suburbs/newport.html": "Private football and soccer coaching for Newport players. About 20 min to our venue at West Point Soccer Club, Point Cook. Juniors to senior-league.",
    "suburbs/point-cook.html": "Private football and soccer coaching in Point Cook. Sessions at West Point Soccer Club, 2 Webster St. Juniors to senior-league, 1-on-1 and small group sessions.",
    "suburbs/tarneit.html": "Private football and soccer coaching for Tarneit players. About 20 min to our venue at West Point Soccer Club, Point Cook. Juniors to senior-league.",
    "suburbs/truganina.html": "Private football and soccer coaching for Truganina players. About 16 min to our venue at West Point Soccer Club, Point Cook. Juniors to senior-league.",
    "suburbs/werribee.html": "Private football and soccer coaching for Werribee players. About 12-15 min via the Princes Freeway to West Point Soccer Club, Point Cook. Juniors to seniors.",
    "suburbs/williams-landing.html": "Private football and soccer coaching for Williams Landing players. About 8 min to our venue at West Point Soccer Club, Point Cook. Juniors to senior-league.",
    "suburbs/williamstown.html": "Private football and soccer coaching for Williamstown players. About 20 min to West Point Soccer Club, Point Cook. Juniors to senior-league or small group.",
    "suburbs/wyndham-vale.html": "Private football and soccer coaching for Wyndham Vale players. About 20 min to our venue at West Point Soccer Club, Point Cook. Juniors to senior-league.",
    "suburbs/index.html": "Private football and soccer coaching across Melbourne's western suburbs. Sessions run at West Point Soccer Club, Point Cook. Find your local service area and drive time.",
}


def business_node():
    h = open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()
    for m in re.finditer(r'<script type="application/ld\+json">(.*?)</script>', h, re.S):
        try:
            d = json.loads(m.group(1))
        except Exception:
            continue
        for node in (d.get("@graph", [d]) if isinstance(d, dict) else [d]):
            t = node.get("@type", "")
            tl = t if isinstance(t, list) else [t]
            if any(x in ("LocalBusiness", "Organization", "SportsOrganization") or x.endswith("Business") for x in tl):
                node = dict(node)
                node.pop("@context", None)
                return node
    return None


def convert_h4(html):
    """Normalise the whole heading outline so no level is skipped. A stack maps
    each original level to a tight emitted level (siblings share it), so an h3
    card sitting directly under an h1 becomes h2, its footer h4 siblings become
    h3, etc. Pages that are already valid are returned unchanged. When an original
    <h4> changes level, the .apf-sub class is added so its Inter (non-display) font
    is kept (h1/h2/h3 all use the Bebas display font, h4 uses Inter)."""
    norm = []   # stack of (orig_level, emitted_level)
    pair = []   # emitted levels, for pairing close tags with their open

    def add_apf_sub(attrs):
        cm = re.search(r'class="([^"]*)"', attrs)
        if cm:
            if "apf-sub" in cm.group(1):
                return attrs
            return attrs[:cm.start(1)] + "apf-sub " + cm.group(1) + attrs[cm.end(1):]
        return ' class="apf-sub"' + attrs

    def rep(m):
        tag = m.group(0)
        lvl = int(m.group(2))
        if m.group(1) == "/":
            return f"</h{pair.pop() if pair else lvl}>"
        while norm and norm[-1][0] >= lvl:
            norm.pop()
        emitted = min(norm[-1][1] + 1 if norm else 1, 6)
        norm.append((lvl, emitted))
        pair.append(emitted)
        if emitted == lvl:
            return tag
        if lvl == 4:
            return f"<h{emitted}{add_apf_sub(tag[3:-1])}>"
        return f"<h{emitted}{tag[3:-1]}>"

    return re.sub(r"<(/?)h([1-6])\b[^>]*>", rep, html)


def patch(fn, biz):
    path = os.path.join(ROOT, fn)
    html = open(path, encoding="utf-8").read()
    orig = html
    did = []

    if fn in TITLES:
        h2 = re.sub(r"<title>.*?</title>", "<title>" + TITLES[fn] + "</title>", html, count=1, flags=re.S)
        if h2 != html:
            html = h2
            did.append(f"title({len(TITLES[fn])})")

    if fn in METAS:
        new = METAS[fn]
        h2 = re.sub(r'(<meta name="description" content=")[^"]*(")',
                    lambda m: m.group(1) + new + m.group(2), html, count=1)
        if h2 != html:
            html = h2
            did.append(f"desc({len(new)})")

    # header wrap (only where no <header> yet)
    if "<header" not in html:
        m = re.search(r'<nav id="main-nav"', html)
        if m:
            close = html.find("</nav>", m.start())
            if close != -1:
                end = close + len("</nav>")
                html = html[:m.start()] + "<header>\n  " + html[m.start():end] + "\n  </header>" + html[end:]
                did.append("header")

    # normalise heading outline (no skips); idempotent on already-valid pages
    hv = convert_h4(html)
    if hv != html:
        html = hv
        did.append("headings")

    # business schema: inject the node on pages that don't define it. Many pages
    # already *reference* the #business @id (WebPage/breadcrumb) without the node,
    # so key off the actual LocalBusiness type, not the @id.
    if biz and '"@type": "LocalBusiness"' not in html:
        block = ('<script type="application/ld+json">\n'
                 + json.dumps({"@context": "https://schema.org", **biz}, indent=2, ensure_ascii=False)
                 + "\n</script>\n")
        html = html.replace("</head>", block + "</head>", 1)
        did.append("business-schema")

    if html != orig:
        open(path, "w", encoding="utf-8").write(html)
    return did


def main():
    biz = business_node()
    print(f"business node: {'found (' + str(biz.get('@type')) + ')' if biz else 'MISSING'}\n")
    files = sorted(glob.glob(os.path.join(ROOT, "*.html")) + glob.glob(os.path.join(ROOT, "*/*.html")))
    for path in files:
        rel = os.path.relpath(path, ROOT)
        if rel in SKIP or rel.startswith("blog/"):
            continue
        print(f"  {rel:40s} {', '.join(patch(rel, biz)) or 'no change'}")
    print("\nDone. Idempotent.")


if __name__ == "__main__":
    main()
